---
title: 6.错误捕捉
---
# 错误：`try()` 语句

常见的错误有以下几种：

* ZeroDivisionError: 除数为 0.
* SyntaxError：语法错误。
* IndexError：索引超界。
* KeyError：字典键不存在。
* IOError：读写错误。 try() 语句的常见写法：

```
try:
    a = 1 
except ZeroDivisionError as e:
    print(e)
    exit()
else:  # 如果无错误，执行
    print(a)
finally:  # 不管有无错误均执行
    print("-- End --")
1
-- End --
```

其中，`else` 与 `finally` 语句都不是必需的。如果不想输出错误信息、或不能预先判断可能的错误类型，可以使用仅含 exit() 语句的 `except` 块。

## 多个 except 块

一个 try 语法块是可以跟着多个 `except` 的；如果靠前的 except 捕获了错误，之后的就不会运行。 这也就是说，如果错误之间有继承关系时，子错误需要放在父错误之前尝试 except，否则子错误永远也不可能被捕获。

比如上一节的例子中，`ZeroDivisionError` 是 `ArithmeticError` 下的子错误，而 `ArithmeticError` 又是 Exception 下的子错误（当不清楚错误的类型时，Exception 可以捕获绝大多数错误）。关于错误的继承关系，参考：Python - Exception Hierarchy 官方页面。

一个例子：

```
try:
    a = 1 / 0
except Exception:
    print("Exception")
    exit()
except ZeroDivisionError:
    print("ZeroDivisionError")
    exit()
else:
    print("No error.")
finally:
    print("-- End --")
输出 Exception 与 – End –。
```

## 错误的捕获

错误在很多地方都可能发生，那是否需要在可能的地方都加上 try 语句呢？当然不是。建议只在主代码中加入 try 语句，因为 Python 会自动跟踪到错误产生的源头何在。

## 错误的抛出及上抛

有时候我们想人为抛出一个错误，这是使用 `raise` 即可：

```
# raise TypeError("Wrong type.")
```

如果在函数中没有处理错误的语句，可能在捕获错误后将其上抛。记住，捕获错误只是为了记录错误的产生，并不意味者必须原地解决错误。

```
def makeerror(n):
    if n == 0:
        raise ValueError("Divided by zero.")
    return 1 / n

def callerror():
    try:
        makeerror(0)
    except ValueError as e:
        print("ValueError detected.")
        raise

# 输出 "ValueError detected." 并打印错误日志
# callerror()
```

上面的 `raise` 命令没有紧跟任何参数，表示将错误原样上抛。你也可以手动指定上抛的错误类型，并不需要与原错误类型一致。甚至你可以定义一个错误（继承某一错误类）：

```
class MyError(ValueError):
    print("This is MyError.")

# raise MyError
This is MyError.
```
